spring:
  thymeleaf:
    #关闭缓存
    cache: false
#    #检查模板文件是否存在
#    check-template: true
#    #检查模本目录是否存在
#    check-template-location: true
    #模板文件编码
#    encoding: UTF-8
#    #模板位置
#    prefix: classpath:/templates/
#    #模板文件后缀名
#    suffix: .html
    #Content-type
#    servlet.content-type: text/html


    #mysql数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    #连接池
    hikari:
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接时间 默认600000（10分钟）1000一秒
      idle-timeout: 180000 #3分钟
      #最大连接数
      maximum-pool-size: 10
      #连接最大存活时间 0表示永久存活,默认1800000(30分钟)
      max-lifetime: 1800000
      #连接超时时间 默认30000
      connection-timeout: 30000
      #从连接池返回的连接自动提交
      auto-commit: true
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  redis:
    host: 192.168.1.217
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数,默认8
        max-active: 8
        #最大连接阻塞等待时间,默认-1
        max-wait: 10000ms
        #最大空闲连接,默认8
        max-idle: 200
        #最小空闲连接,默认0
        min-idle: 5
    password: 123


mybatis-plus:
  #配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置数据返回类型的别名
  type-aliases-package: com.lifu.seckill.pojo


# MyBatis SQL打印(方法接口所在的包)
logging:
  level:
    com.lifu.seckill.mapper: debug

